name: cooking_app_flutter
description: Cooking app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#   Service locator
  get_it: ^7.2.0
#   Allows value based equality for our classes e.g Eat() == Eat() is true
  equatable: ^2.0.5
#   Generates code by providing annotations
  injectable: ^1.5.3
#   Allows converting json to dart class and back
  json_serializable: ^6.5.0
  json_annotation: ^4.7.0
#   Linting
  very_good_analysis: ^3.1.0
#   Icons
  cupertino_icons: ^1.0.5
#   Data classes generator
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
#   Firebase
  firebase_core: ^1.24.0
#   Firebase auth
  firebase_auth: ^3.11.2
#   Firebase database
  cloud_firestore: ^3.5.1
#   Firebase storage
  firebase_storage: ^10.3.11
  #   Email validator
  email_validator: ^2.1.17
#   Picking images
  image_picker: ^0.8.6
#   Permissions handling
  permission_handler: ^10.1.0
#  Reactive
  rxdart: ^0.27.5
#  Collections utilities
  collection: ^1.16.0
# Bottom number picker:
  bottom_picker: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.1
  injectable_generator: ^1.5.4
  test: ^1.21.4

flutter:

  uses-material-design: true

  assets:
    - assets/graphics/