name: cooking_app_flutter
description: Cooking app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  moor_flutter: ^4.1.0

#  UI
  provider: ^6.0.3


  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  moor_generator: ^4.6.0+1

flutter:

  uses-material-design: true