name: cooking_app_flutter
description: Cooking app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^1.19.1
# Firebase auth
  firebase_auth: ^3.4.1
# Firebase database
  cloud_firestore: ^3.2.1
#  Email validator
  email_validator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  moor_generator: ^4.6.0+1

flutter:

  uses-material-design: true