name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  flutter_test:
    name: Run flutter tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Decode secrets
        env:
          SECRET_DOT_ENV: ${{ secrets.SECRET_DOT_ENV }}
        run: |
          echo $SECRET_DOT_ENV | base64 -d > .env
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter test
